X=msgbox("Ola galera do ifanny",32,"Shrek Script")
X=msgbox("Vim trazer pra voces um Script do Shrek (Pt-Br) para whatsapp",48,"Shrek Script")
X=msgbox("Para baixar Pesquise no google (github ChickChuck2)",48,"ChickChuck2 Github")
X=msgbox("E encontre o repositorio Shrek_Script-Whatsapp",48,"ChickChuck2 Github")
X=msgbox("Eu deixo o tutorial no meu repositorio",16,"ChickChuck2 Github")
X=msgbox("Mas vou mostrar que esse Script funciona",48,"Curto Rock")